logo: /assets/css/headshot.png
title: Cyrus C. Baruc
description: Business Analyst | Business Intelligence Analyst
show_downloads: false
theme: jekyll-theme-minimal
include:
  - assets/css/styles.css
