title: " "
logo: ![Cyrus Baruc Headshot](/assets/css/headshot.png){: .headshot }
description: Business Analyst | Power BI Developer
show_downloads: false
theme: jekyll-theme-minimal
include:
  - assets/css/styles.css
